### ISSUE TITLE
Need any help on turning more of these green?

### ISSUE THREAD

**Issue by cclauss** [julianoes/PX4-Python-tests#4]
Last test was 16 days ago.

**Comment by julianoes** [comment]
Yes please, thanks! I think we should continue in https://github.com/PX4/containers/pulls which will then enable Firmware and others based on it.

**Comment by julianoes** [comment]
Firmware and containers is finally all on Python 3 :tada:. The outstanding one now is probably the NuttX repos but there we're mostly just using the fork downstream (with a few exceptions).
